### ISSUE TITLE
Salvare i Feed e i termini in Elasticsearch

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/wheretolive-api#6]
1. Vedere la forma delle case class da utilizzare
2. aggiungere il codice per salvare https://github.com/sksamuel/elastic4s

**Comment by fabiofumarola** [comment]
Ieri sera ho dato una occhiata ad elastic4s e le api java di elasticsearch. Entrambi permettono di passare raw query via driver binario.

## [Esempio elastic4s](https://github.com/sksamuel/elastic4s/blob/4eabea12d53ad0a3bb32b71b5f46e04782b58786/elastic4s-core-tests/src/test/scala/com/sksamuel/elastic4s/query/RawQueryTest.scala)

``` scala

package com.sksamuel.elastic4s.query

import com.sksamuel.elastic4s.ElasticDsl
import org.scalatest.{ Matchers, WordSpec }
import com.sksamuel.elastic4s.testkit.ElasticSugar

class RawQueryTest extends WordSpec with ElasticSugar with Matchers {

  import ElasticDsl._

  client.execute {
    bulk(
      index into "rawquerytest/paris" fields ("landmark" -> "montmarte", "arrondissement" -> "18"),
      index into "rawquerytest/paris" fields ("landmark" -> "le tower eiffel", "arrondissement" -> "7")
    )
  }.await

  blockUntilCount(2, "rawquerytest")

  "raw query" should {
    "work!" in {
      val hits = client.execute {
        search in "*" types ("rawquerytest", "paris") limit 5 rawQuery {
          """{ "prefix": { "landmark": { "prefix": "montm" } } }"""
        }
      }.await.getHits.totalHits
      assert(hits === 1)
    }
  }
}
```

## [Esempio Java](http://teknosrc.com/execute-raw-elasticsearch-query-using-transport-client-java-api/)

**Comment by fabiofumarola** [comment]
Quindi e' possibile specificando indice e document type inviare una query completamente codificata come stringa

**Comment by fabiana001** [comment]
nessuno ieri parlava del problema delle query, il problema era relativo all'impostazione dei setting e mapping, che in elastic4s non era banale (questo non sign che non si possa fare)

**Comment by fabiofumarola** [comment]
avevo capito delle query. I mapping si possono fare in qualunque modo

2016-02-11 10:03 GMT+01:00 Fabiana Lanotte notifications@github.com:

> nessuno ieri parlava del problema delle query, il problema era relativo
> all'impostazione dei setting e mapping, che in elastic4s non era banale
> (questo non sign che non si possa fare)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DataToKnowledge/wheretolive-api/issues/6#issuecomment-182773380
> .

## 

---

Fabio Fumarola Ph.D.

Department of Computer Science, University of Bari "Aldo Moro"
Via E. Orabona, 4 - Bari 71025 Italy
Tel: +39 - 0805442299
Mobile: +39 - 3292338896
Fax: +39 - 0805443269
http://www.di.uniba.it/~fumarola/
https://www.linkedin.com/pub/fabio-fumarola/7/540/605
mailto:ffumarola@di.uniba.it
mailto:fumarola@illinois.edu
